diff_drive_controller:
  type: 'diff_drive_controller/DiffDriveController'

  left_wheel:
   - 'front_left_wheel_joint'
   - 'rear_left_wheel_joint'

  right_wheel:
   - 'front_right_wheel_joint'
   - 'rear_right_wheel_joint'

  publish_rate: 50

  pose_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 1000.0]
  cmd_vel_timeout: 0.25

  enable_odom_tf: false

  # Base frame_id
  base_frame_id: base_link

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier: 1.0 # default: 1.0

  wheel_separation: 0.26
  wheel_radius: 0.035

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration: 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration: 25.0   # rad/s^2
