ekf_localization:
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  two_d_mode: true

  frequency: 4

  odom0: diff_drive_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true, false, false,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  odom0_queue_size: 10

  imu0: imu
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                true, true, true,
                true, true, true]
  imu0_differential: true
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true
