<robot name="carmen" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find carmen_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find carmen_description)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find carmen_description)/urdf/sensors/camera.urdf.xacro"/>
  <xacro:include filename="$(find carmen_description)/urdf/sensors/sonar.urdf.xacro"/>
  <xacro:include filename="$(find carmen_description)/urdf/wheels.urdf.xacro"/>

  <xacro:property name="base_width" value="0.3"/>
  <xacro:property name="base_length" value="0.2"/>
  <xacro:property name="base_height" value="0.05"/>
  <xacro:property name="base_mass" value="0.4"/>

  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_mass" value="1"/>

  <xacro:property name="bearing_radius" value="0.005"/>

  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${base_height / 2 + wheel_radius - bearing_radius}"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <xacro:box_geometry width="${base_width}" length="${base_length}" height="${base_height}"/>
      <xacro:yellow_material/>
    </visual>
    <xacro:box_collision width="${base_width}" length="${base_length}" height="${base_height}"/>
    <xacro:box_inertia width="${base_width}" length="${base_length}" height="${base_height}" mass="${base_mass}"/>
  </link>

  <xacro:simple_camera prefix="left" parent_link_name="base_link" parent_height="${base_height}"
                       parent_length="${base_length / 2}" side="1"/>
  <xacro:simple_camera prefix="right" parent_link_name="base_link" parent_height="${base_height}"
                       parent_length="${base_length / 2}" side="-1"/>

  <xacro:wheel prefix="front_left" direction="1" bearing_radius="${bearing_radius}" radius="${wheel_radius}"
               width="${wheel_width}" mass="${wheel_mass}" distance_between_wheels="${base_length}"
               x="${base_width / 4}" z="${bearing_radius - base_height / 2}"/>
  <xacro:wheel prefix="front_right" direction="-1" bearing_radius="${bearing_radius}" radius="${wheel_radius}"
               width="${wheel_width}" mass="${wheel_mass}" distance_between_wheels="${base_length}"
               x="${base_width / 4}" z="${bearing_radius - base_height / 2}"/>
  <xacro:wheel prefix="rear_left" direction="1" bearing_radius="${bearing_radius}" radius="${wheel_radius}"
               width="${wheel_width}" mass="${wheel_mass}" distance_between_wheels="${base_length}"
               x="${-base_width / 4}" z="${bearing_radius - base_height / 2}"/>
  <xacro:wheel prefix="rear_right" direction="-1" bearing_radius="${bearing_radius}" radius="${wheel_radius}"
               width="${wheel_width}" mass="${wheel_mass}" distance_between_wheels="${base_length}"
               x="${-base_width / 4}" z="${bearing_radius - base_height / 2}"/>

</robot>
