//.$file${../include::public::communication_base.h} vvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: carmen.qm
// File:  ${../include::public::communication_base.h}
//
// This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
// DO NOT EDIT SECTIONS BETWEEN THE COMMENTS "$...vvv".."$end...^^^".
// All your changes in these sections will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${../include::public::communication_base.h} ^^^^^^^^^^^^^^^^^^^^^^^
#include <stdint.h>
#include "qpcpp.h"
#include "types.h"
#include "events.h"

//.$declare${application::CommunicationBase} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace carmen_hardware {

//.${application::CommunicationBase} .........................................
class CommunicationBase : public QP::QActive {
protected:
    virtual void setImuHandler(SetImuEvt const* event) = 0;
    virtual void setEncodersHandler() = 0;
    virtual void commandHandler() = 0;

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(idle);
};

} // namespace carmen_hardware
//.$enddecl${application::CommunicationBase} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
