//.$file${../include::public::signals.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: carmen.qm
// File:  ${../include::public::signals.h}
//
// This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
// DO NOT EDIT SECTIONS BETWEEN THE COMMENTS "$...vvv".."$end...^^^".
// All your changes in these sections will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${../include::public::signals.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#include "qpcpp.h"
#include "types.h"

enum CarmenSignals {
   COM_SET_IMU_SIG = Q_USER_SIG,
   COM_SET_ENCODERS_SIG,
   COM_COMMAND_SIG
};

//.$declare${events::SetImuEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace carmen_hardware {

//.${events::SetImuEvt} ......................................................
class SetImuEvt : public QP::QEvt {
public:
    application::ImuData data;
};

} // namespace carmen_hardware
//.$enddecl${events::SetImuEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
