diff_drive_controller:
  type: 'diff_drive_controller/DiffDriveController'
  left_wheel:
   - 'front_left_wheel_joint'
   - 'rear_left_wheel_joint'
  right_wheel:
   - 'front_right_wheel_joint'
   - 'rear_right_wheel_joint'
  publish_rate: 50.0 # defaults to 50 Hz
  pose_covariance_diagonal: [0.01, 0.01, 1000000.0, 1000000.0, 1000000.0, 1.0] #[0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.01, 1000000.0, 1000000.0, 1000000.0, 1000000.0, 1.0] #[0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation: 0.55
  wheel_radius: 0.10

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: base_footprint #default: base_link

  enable_odom_tf: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.7  # m/s
      min_velocity           : -0.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # m/s^2
      min_acceleration       : -0.4 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 1.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.15  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.1  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 0.2  # rad/s^3