four_wheel_controller:
  type: 'four_wheel_steering_controller/FourWheelSteeringController'
  front_wheel: 
    - 'front_left_wheel_link'
    - 'front_right_wheel_link'
  rear_wheel:
    - 'rear_left_wheel_link'
    - 'rear_right_wheel_link'
  front_steering: 
    - 'front_left_wheel_bearing_joint'
    - 'front_right_wheel_bearing_joint'
  rear_steering:
    - 'rear_left_wheel_bearing_joint'
    - 'rear_right_wheel_bearing_joint'
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 25.0

  base_frame_id: base_footprint

  enable_odom_tf: true

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.5   # m/s^2
    y:
      has_velocity_limits    : true
      max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.5   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.0   # rad/s^2
