local_costmap:
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 2.0
      publish_frequency: 1.5
      static_map: false
      rolling_window: true
      width: 5.0
      height: 5.0
      resolution: 0.1
      transform_tolerance: 0.5
      planner_frequency: 1.0
      planner_patiente: 5.0
